name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.8.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: nx-mf-df/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: nx-mf-df

      - run: pnpm run ghBuildProd:all
        working-directory: nx-mf-df

      - run: pnpm run ghDeploy:all
        working-directory: nx-mf-df
